// <auto-generated />
namespace Furst_Alpha_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vendor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vendor));
        
        string IMigrationMetadata.Id
        {
            get { return "201611210319446_Vendor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
